version: 2

project_name: context

before:
  hooks:
    - go mod tidy

builds:
  - id: context
    main: ./cmd/context
    binary: context

    env:
      - CGO_ENABLED=0

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: meesakveld
    name: context